// flow-typed signature: acdeb11a43efae717eec434a901b9984
// flow-typed version: <<STUB>>/material-design-lite_v^1.2.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-design-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-design-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-design-lite/dist/assets/codepen' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/components' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/customizer' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/index' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/main' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/prism-bash.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/prism-css.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/prism-javascript.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/prism-markup.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/prism' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/assets/snippets' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/components/animation/demo' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/material' {
  declare module.exports: any;
}

declare module 'material-design-lite/dist/material.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'material-design-lite/material' {
  declare module.exports: any;
}

declare module 'material-design-lite/material.min' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/animation/demo' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/button/button' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/checkbox/checkbox' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/data-table/data-table' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/icon-toggle/icon-toggle' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/layout/layout' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/mdlComponentHandler' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/menu/menu' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/progress/progress' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/radio/radio' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/ripple/ripple' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/slider/slider' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/snackbar/snackbar' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/spinner/spinner' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/switch/switch' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/tabs/tabs' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/textfield/textfield' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/third_party/rAF' {
  declare module.exports: any;
}

declare module 'material-design-lite/src/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'material-design-lite/utils/jscs-rules/closure-camel-case' {
  declare module.exports: any;
}

declare module 'material-design-lite/utils/uniffe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-design-lite/dist/assets/codepen.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/codepen'>;
}
declare module 'material-design-lite/dist/assets/components.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/components'>;
}
declare module 'material-design-lite/dist/assets/customizer.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/customizer'>;
}
declare module 'material-design-lite/dist/assets/index.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/index'>;
}
declare module 'material-design-lite/dist/assets/main.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/main'>;
}
declare module 'material-design-lite/dist/assets/prism-bash.min.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/prism-bash.min'>;
}
declare module 'material-design-lite/dist/assets/prism-css.min.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/prism-css.min'>;
}
declare module 'material-design-lite/dist/assets/prism-javascript.min.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/prism-javascript.min'>;
}
declare module 'material-design-lite/dist/assets/prism-markup.min.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/prism-markup.min'>;
}
declare module 'material-design-lite/dist/assets/prism.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/prism'>;
}
declare module 'material-design-lite/dist/assets/snippets.js' {
  declare module.exports: $Exports<'material-design-lite/dist/assets/snippets'>;
}
declare module 'material-design-lite/dist/components/animation/demo.js' {
  declare module.exports: $Exports<'material-design-lite/dist/components/animation/demo'>;
}
declare module 'material-design-lite/dist/material.js' {
  declare module.exports: $Exports<'material-design-lite/dist/material'>;
}
declare module 'material-design-lite/dist/material.min.js' {
  declare module.exports: $Exports<'material-design-lite/dist/material.min'>;
}
declare module 'material-design-lite/gulpfile.babel.js' {
  declare module.exports: $Exports<'material-design-lite/gulpfile.babel'>;
}
declare module 'material-design-lite/material.js' {
  declare module.exports: $Exports<'material-design-lite/material'>;
}
declare module 'material-design-lite/material.min.js' {
  declare module.exports: $Exports<'material-design-lite/material.min'>;
}
declare module 'material-design-lite/src/animation/demo.js' {
  declare module.exports: $Exports<'material-design-lite/src/animation/demo'>;
}
declare module 'material-design-lite/src/button/button.js' {
  declare module.exports: $Exports<'material-design-lite/src/button/button'>;
}
declare module 'material-design-lite/src/checkbox/checkbox.js' {
  declare module.exports: $Exports<'material-design-lite/src/checkbox/checkbox'>;
}
declare module 'material-design-lite/src/data-table/data-table.js' {
  declare module.exports: $Exports<'material-design-lite/src/data-table/data-table'>;
}
declare module 'material-design-lite/src/icon-toggle/icon-toggle.js' {
  declare module.exports: $Exports<'material-design-lite/src/icon-toggle/icon-toggle'>;
}
declare module 'material-design-lite/src/layout/layout.js' {
  declare module.exports: $Exports<'material-design-lite/src/layout/layout'>;
}
declare module 'material-design-lite/src/mdlComponentHandler.js' {
  declare module.exports: $Exports<'material-design-lite/src/mdlComponentHandler'>;
}
declare module 'material-design-lite/src/menu/menu.js' {
  declare module.exports: $Exports<'material-design-lite/src/menu/menu'>;
}
declare module 'material-design-lite/src/progress/progress.js' {
  declare module.exports: $Exports<'material-design-lite/src/progress/progress'>;
}
declare module 'material-design-lite/src/radio/radio.js' {
  declare module.exports: $Exports<'material-design-lite/src/radio/radio'>;
}
declare module 'material-design-lite/src/ripple/ripple.js' {
  declare module.exports: $Exports<'material-design-lite/src/ripple/ripple'>;
}
declare module 'material-design-lite/src/slider/slider.js' {
  declare module.exports: $Exports<'material-design-lite/src/slider/slider'>;
}
declare module 'material-design-lite/src/snackbar/snackbar.js' {
  declare module.exports: $Exports<'material-design-lite/src/snackbar/snackbar'>;
}
declare module 'material-design-lite/src/spinner/spinner.js' {
  declare module.exports: $Exports<'material-design-lite/src/spinner/spinner'>;
}
declare module 'material-design-lite/src/switch/switch.js' {
  declare module.exports: $Exports<'material-design-lite/src/switch/switch'>;
}
declare module 'material-design-lite/src/tabs/tabs.js' {
  declare module.exports: $Exports<'material-design-lite/src/tabs/tabs'>;
}
declare module 'material-design-lite/src/textfield/textfield.js' {
  declare module.exports: $Exports<'material-design-lite/src/textfield/textfield'>;
}
declare module 'material-design-lite/src/third_party/rAF.js' {
  declare module.exports: $Exports<'material-design-lite/src/third_party/rAF'>;
}
declare module 'material-design-lite/src/tooltip/tooltip.js' {
  declare module.exports: $Exports<'material-design-lite/src/tooltip/tooltip'>;
}
declare module 'material-design-lite/utils/jscs-rules/closure-camel-case.js' {
  declare module.exports: $Exports<'material-design-lite/utils/jscs-rules/closure-camel-case'>;
}
declare module 'material-design-lite/utils/uniffe.js' {
  declare module.exports: $Exports<'material-design-lite/utils/uniffe'>;
}
