// flow-typed signature: 0f558ba4f21ab517d2fb12f88813f69e
// flow-typed version: <<STUB>>/postcss-flexbugs-fixes_v^2.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-flexbugs-fixes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-flexbugs-fixes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-flexbugs-fixes/bugs/bug4' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/bugs/bug6' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/bugs/bug81a' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/specs/bug4Spec' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/specs/bug6Spec' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/specs/bug81aSpec' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/specs/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-flexbugs-fixes/bugs/bug4.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug4'>;
}
declare module 'postcss-flexbugs-fixes/bugs/bug6.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug6'>;
}
declare module 'postcss-flexbugs-fixes/bugs/bug81a.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug81a'>;
}
declare module 'postcss-flexbugs-fixes/index' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes'>;
}
declare module 'postcss-flexbugs-fixes/index.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes'>;
}
declare module 'postcss-flexbugs-fixes/specs/bug4Spec.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/specs/bug4Spec'>;
}
declare module 'postcss-flexbugs-fixes/specs/bug6Spec.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/specs/bug6Spec'>;
}
declare module 'postcss-flexbugs-fixes/specs/bug81aSpec.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/specs/bug81aSpec'>;
}
declare module 'postcss-flexbugs-fixes/specs/test.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/specs/test'>;
}
