// flow-typed signature: b354b3c9a46f7a41960b47072ea7e38c
// flow-typed version: <<STUB>>/react-mdl_v^1.7.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mdl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mdl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mdl/extra/material' {
  declare module.exports: any;
}

declare module 'react-mdl/extra/material.min' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Badge/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Button' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Card/Card' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Card/CardActions' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Card/CardTitle' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Card/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Chip/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/DataTable/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/DataTable/Selectable' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/DataTable/Sortable' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/DataTable/Table' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/DataTable/TableHeader' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Dialog/DialogActions' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Dialog/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Dialog/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/FABButton' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Footer/DropDownSection' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Footer/Footer' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Footer/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Footer/LinkList' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Footer/Section' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Grid/Cell' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Grid/Grid' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Grid/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Icon/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/IconButton' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/IconToggle' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Content' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Drawer' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Header' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/HeaderRow' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/HeaderTabs' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Layout' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Navigation' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Layout/Spacer' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/List/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/List/ListItem' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/List/ListItemAction' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/List/ListItemContent' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Menu' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Radio' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/RadioGroup' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Slider' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Snackbar/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Spinner' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Switch' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Tabs/index' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Tabs/Tab' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Tabs/TabBar' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Tabs/Tabs' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Textfield' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/basicClassCreator' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/cloneChildren' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/MDLComponent' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/mdlUpgrade' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/palette' {
  declare module.exports: any;
}

declare module 'react-mdl/lib/utils/shadows' {
  declare module.exports: any;
}

declare module 'react-mdl/out/ReactMDL' {
  declare module.exports: any;
}

declare module 'react-mdl/out/ReactMDL.min' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Badge/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Button' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Card/Card' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Card/CardActions' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Card/CardTitle' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Card/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Checkbox' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Chip/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/DataTable/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/DataTable/Selectable' {
  declare module.exports: any;
}

declare module 'react-mdl/src/DataTable/Sortable' {
  declare module.exports: any;
}

declare module 'react-mdl/src/DataTable/Table' {
  declare module.exports: any;
}

declare module 'react-mdl/src/DataTable/TableHeader' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Dialog/DialogActions' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Dialog/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Dialog/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/FABButton' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Footer/DropDownSection' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Footer/Footer' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Footer/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Footer/LinkList' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Footer/Section' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Grid/Cell' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Grid/Grid' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Grid/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Icon/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/IconButton' {
  declare module.exports: any;
}

declare module 'react-mdl/src/IconToggle' {
  declare module.exports: any;
}

declare module 'react-mdl/src/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Content' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Drawer' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Header' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/HeaderRow' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/HeaderTabs' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Layout' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Navigation' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Layout/Spacer' {
  declare module.exports: any;
}

declare module 'react-mdl/src/List/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/List/ListItem' {
  declare module.exports: any;
}

declare module 'react-mdl/src/List/ListItemAction' {
  declare module.exports: any;
}

declare module 'react-mdl/src/List/ListItemContent' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Menu' {
  declare module.exports: any;
}

declare module 'react-mdl/src/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Radio' {
  declare module.exports: any;
}

declare module 'react-mdl/src/RadioGroup' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Slider' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Snackbar/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Spinner' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Switch' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Tabs/index' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Tabs/Tab' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Tabs/TabBar' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Tabs/Tabs' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Textfield' {
  declare module.exports: any;
}

declare module 'react-mdl/src/Tooltip' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/basicClassCreator' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/cloneChildren' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/MDLComponent' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/mdlUpgrade' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/palette' {
  declare module.exports: any;
}

declare module 'react-mdl/src/utils/shadows' {
  declare module.exports: any;
}

declare module 'react-mdl/tests.webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mdl/extra/material.js' {
  declare module.exports: $Exports<'react-mdl/extra/material'>;
}
declare module 'react-mdl/extra/material.min.js' {
  declare module.exports: $Exports<'react-mdl/extra/material.min'>;
}
declare module 'react-mdl/lib/Badge/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Badge/index'>;
}
declare module 'react-mdl/lib/Button.js' {
  declare module.exports: $Exports<'react-mdl/lib/Button'>;
}
declare module 'react-mdl/lib/Card/Card.js' {
  declare module.exports: $Exports<'react-mdl/lib/Card/Card'>;
}
declare module 'react-mdl/lib/Card/CardActions.js' {
  declare module.exports: $Exports<'react-mdl/lib/Card/CardActions'>;
}
declare module 'react-mdl/lib/Card/CardTitle.js' {
  declare module.exports: $Exports<'react-mdl/lib/Card/CardTitle'>;
}
declare module 'react-mdl/lib/Card/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Card/index'>;
}
declare module 'react-mdl/lib/Checkbox.js' {
  declare module.exports: $Exports<'react-mdl/lib/Checkbox'>;
}
declare module 'react-mdl/lib/Chip/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Chip/index'>;
}
declare module 'react-mdl/lib/DataTable/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/DataTable/index'>;
}
declare module 'react-mdl/lib/DataTable/Selectable.js' {
  declare module.exports: $Exports<'react-mdl/lib/DataTable/Selectable'>;
}
declare module 'react-mdl/lib/DataTable/Sortable.js' {
  declare module.exports: $Exports<'react-mdl/lib/DataTable/Sortable'>;
}
declare module 'react-mdl/lib/DataTable/Table.js' {
  declare module.exports: $Exports<'react-mdl/lib/DataTable/Table'>;
}
declare module 'react-mdl/lib/DataTable/TableHeader.js' {
  declare module.exports: $Exports<'react-mdl/lib/DataTable/TableHeader'>;
}
declare module 'react-mdl/lib/Dialog/Dialog.js' {
  declare module.exports: $Exports<'react-mdl/lib/Dialog/Dialog'>;
}
declare module 'react-mdl/lib/Dialog/DialogActions.js' {
  declare module.exports: $Exports<'react-mdl/lib/Dialog/DialogActions'>;
}
declare module 'react-mdl/lib/Dialog/DialogTitle.js' {
  declare module.exports: $Exports<'react-mdl/lib/Dialog/DialogTitle'>;
}
declare module 'react-mdl/lib/Dialog/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Dialog/index'>;
}
declare module 'react-mdl/lib/FABButton.js' {
  declare module.exports: $Exports<'react-mdl/lib/FABButton'>;
}
declare module 'react-mdl/lib/Footer/DropDownSection.js' {
  declare module.exports: $Exports<'react-mdl/lib/Footer/DropDownSection'>;
}
declare module 'react-mdl/lib/Footer/Footer.js' {
  declare module.exports: $Exports<'react-mdl/lib/Footer/Footer'>;
}
declare module 'react-mdl/lib/Footer/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Footer/index'>;
}
declare module 'react-mdl/lib/Footer/LinkList.js' {
  declare module.exports: $Exports<'react-mdl/lib/Footer/LinkList'>;
}
declare module 'react-mdl/lib/Footer/Section.js' {
  declare module.exports: $Exports<'react-mdl/lib/Footer/Section'>;
}
declare module 'react-mdl/lib/Grid/Cell.js' {
  declare module.exports: $Exports<'react-mdl/lib/Grid/Cell'>;
}
declare module 'react-mdl/lib/Grid/Grid.js' {
  declare module.exports: $Exports<'react-mdl/lib/Grid/Grid'>;
}
declare module 'react-mdl/lib/Grid/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Grid/index'>;
}
declare module 'react-mdl/lib/Icon/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Icon/index'>;
}
declare module 'react-mdl/lib/IconButton.js' {
  declare module.exports: $Exports<'react-mdl/lib/IconButton'>;
}
declare module 'react-mdl/lib/IconToggle.js' {
  declare module.exports: $Exports<'react-mdl/lib/IconToggle'>;
}
declare module 'react-mdl/lib/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/index'>;
}
declare module 'react-mdl/lib/Layout/Content.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Content'>;
}
declare module 'react-mdl/lib/Layout/Drawer.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Drawer'>;
}
declare module 'react-mdl/lib/Layout/Header.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Header'>;
}
declare module 'react-mdl/lib/Layout/HeaderRow.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/HeaderRow'>;
}
declare module 'react-mdl/lib/Layout/HeaderTabs.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/HeaderTabs'>;
}
declare module 'react-mdl/lib/Layout/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/index'>;
}
declare module 'react-mdl/lib/Layout/Layout.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Layout'>;
}
declare module 'react-mdl/lib/Layout/Navigation.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Navigation'>;
}
declare module 'react-mdl/lib/Layout/Spacer.js' {
  declare module.exports: $Exports<'react-mdl/lib/Layout/Spacer'>;
}
declare module 'react-mdl/lib/List/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/List/index'>;
}
declare module 'react-mdl/lib/List/ListItem.js' {
  declare module.exports: $Exports<'react-mdl/lib/List/ListItem'>;
}
declare module 'react-mdl/lib/List/ListItemAction.js' {
  declare module.exports: $Exports<'react-mdl/lib/List/ListItemAction'>;
}
declare module 'react-mdl/lib/List/ListItemContent.js' {
  declare module.exports: $Exports<'react-mdl/lib/List/ListItemContent'>;
}
declare module 'react-mdl/lib/Menu.js' {
  declare module.exports: $Exports<'react-mdl/lib/Menu'>;
}
declare module 'react-mdl/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-mdl/lib/ProgressBar'>;
}
declare module 'react-mdl/lib/Radio.js' {
  declare module.exports: $Exports<'react-mdl/lib/Radio'>;
}
declare module 'react-mdl/lib/RadioGroup.js' {
  declare module.exports: $Exports<'react-mdl/lib/RadioGroup'>;
}
declare module 'react-mdl/lib/Slider.js' {
  declare module.exports: $Exports<'react-mdl/lib/Slider'>;
}
declare module 'react-mdl/lib/Snackbar/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Snackbar/index'>;
}
declare module 'react-mdl/lib/Spinner.js' {
  declare module.exports: $Exports<'react-mdl/lib/Spinner'>;
}
declare module 'react-mdl/lib/Switch.js' {
  declare module.exports: $Exports<'react-mdl/lib/Switch'>;
}
declare module 'react-mdl/lib/Tabs/index.js' {
  declare module.exports: $Exports<'react-mdl/lib/Tabs/index'>;
}
declare module 'react-mdl/lib/Tabs/Tab.js' {
  declare module.exports: $Exports<'react-mdl/lib/Tabs/Tab'>;
}
declare module 'react-mdl/lib/Tabs/TabBar.js' {
  declare module.exports: $Exports<'react-mdl/lib/Tabs/TabBar'>;
}
declare module 'react-mdl/lib/Tabs/Tabs.js' {
  declare module.exports: $Exports<'react-mdl/lib/Tabs/Tabs'>;
}
declare module 'react-mdl/lib/Textfield.js' {
  declare module.exports: $Exports<'react-mdl/lib/Textfield'>;
}
declare module 'react-mdl/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-mdl/lib/Tooltip'>;
}
declare module 'react-mdl/lib/utils/basicClassCreator.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/basicClassCreator'>;
}
declare module 'react-mdl/lib/utils/cloneChildren.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/cloneChildren'>;
}
declare module 'react-mdl/lib/utils/MDLComponent.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/MDLComponent'>;
}
declare module 'react-mdl/lib/utils/mdlUpgrade.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/mdlUpgrade'>;
}
declare module 'react-mdl/lib/utils/palette.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/palette'>;
}
declare module 'react-mdl/lib/utils/shadows.js' {
  declare module.exports: $Exports<'react-mdl/lib/utils/shadows'>;
}
declare module 'react-mdl/out/ReactMDL.js' {
  declare module.exports: $Exports<'react-mdl/out/ReactMDL'>;
}
declare module 'react-mdl/out/ReactMDL.min.js' {
  declare module.exports: $Exports<'react-mdl/out/ReactMDL.min'>;
}
declare module 'react-mdl/src/Badge/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Badge/index'>;
}
declare module 'react-mdl/src/Button.js' {
  declare module.exports: $Exports<'react-mdl/src/Button'>;
}
declare module 'react-mdl/src/Card/Card.js' {
  declare module.exports: $Exports<'react-mdl/src/Card/Card'>;
}
declare module 'react-mdl/src/Card/CardActions.js' {
  declare module.exports: $Exports<'react-mdl/src/Card/CardActions'>;
}
declare module 'react-mdl/src/Card/CardTitle.js' {
  declare module.exports: $Exports<'react-mdl/src/Card/CardTitle'>;
}
declare module 'react-mdl/src/Card/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Card/index'>;
}
declare module 'react-mdl/src/Checkbox.js' {
  declare module.exports: $Exports<'react-mdl/src/Checkbox'>;
}
declare module 'react-mdl/src/Chip/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Chip/index'>;
}
declare module 'react-mdl/src/DataTable/index.js' {
  declare module.exports: $Exports<'react-mdl/src/DataTable/index'>;
}
declare module 'react-mdl/src/DataTable/Selectable.js' {
  declare module.exports: $Exports<'react-mdl/src/DataTable/Selectable'>;
}
declare module 'react-mdl/src/DataTable/Sortable.js' {
  declare module.exports: $Exports<'react-mdl/src/DataTable/Sortable'>;
}
declare module 'react-mdl/src/DataTable/Table.js' {
  declare module.exports: $Exports<'react-mdl/src/DataTable/Table'>;
}
declare module 'react-mdl/src/DataTable/TableHeader.js' {
  declare module.exports: $Exports<'react-mdl/src/DataTable/TableHeader'>;
}
declare module 'react-mdl/src/Dialog/Dialog.js' {
  declare module.exports: $Exports<'react-mdl/src/Dialog/Dialog'>;
}
declare module 'react-mdl/src/Dialog/DialogActions.js' {
  declare module.exports: $Exports<'react-mdl/src/Dialog/DialogActions'>;
}
declare module 'react-mdl/src/Dialog/DialogTitle.js' {
  declare module.exports: $Exports<'react-mdl/src/Dialog/DialogTitle'>;
}
declare module 'react-mdl/src/Dialog/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Dialog/index'>;
}
declare module 'react-mdl/src/FABButton.js' {
  declare module.exports: $Exports<'react-mdl/src/FABButton'>;
}
declare module 'react-mdl/src/Footer/DropDownSection.js' {
  declare module.exports: $Exports<'react-mdl/src/Footer/DropDownSection'>;
}
declare module 'react-mdl/src/Footer/Footer.js' {
  declare module.exports: $Exports<'react-mdl/src/Footer/Footer'>;
}
declare module 'react-mdl/src/Footer/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Footer/index'>;
}
declare module 'react-mdl/src/Footer/LinkList.js' {
  declare module.exports: $Exports<'react-mdl/src/Footer/LinkList'>;
}
declare module 'react-mdl/src/Footer/Section.js' {
  declare module.exports: $Exports<'react-mdl/src/Footer/Section'>;
}
declare module 'react-mdl/src/Grid/Cell.js' {
  declare module.exports: $Exports<'react-mdl/src/Grid/Cell'>;
}
declare module 'react-mdl/src/Grid/Grid.js' {
  declare module.exports: $Exports<'react-mdl/src/Grid/Grid'>;
}
declare module 'react-mdl/src/Grid/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Grid/index'>;
}
declare module 'react-mdl/src/Icon/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Icon/index'>;
}
declare module 'react-mdl/src/IconButton.js' {
  declare module.exports: $Exports<'react-mdl/src/IconButton'>;
}
declare module 'react-mdl/src/IconToggle.js' {
  declare module.exports: $Exports<'react-mdl/src/IconToggle'>;
}
declare module 'react-mdl/src/index.js' {
  declare module.exports: $Exports<'react-mdl/src/index'>;
}
declare module 'react-mdl/src/Layout/Content.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Content'>;
}
declare module 'react-mdl/src/Layout/Drawer.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Drawer'>;
}
declare module 'react-mdl/src/Layout/Header.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Header'>;
}
declare module 'react-mdl/src/Layout/HeaderRow.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/HeaderRow'>;
}
declare module 'react-mdl/src/Layout/HeaderTabs.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/HeaderTabs'>;
}
declare module 'react-mdl/src/Layout/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/index'>;
}
declare module 'react-mdl/src/Layout/Layout.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Layout'>;
}
declare module 'react-mdl/src/Layout/Navigation.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Navigation'>;
}
declare module 'react-mdl/src/Layout/Spacer.js' {
  declare module.exports: $Exports<'react-mdl/src/Layout/Spacer'>;
}
declare module 'react-mdl/src/List/index.js' {
  declare module.exports: $Exports<'react-mdl/src/List/index'>;
}
declare module 'react-mdl/src/List/ListItem.js' {
  declare module.exports: $Exports<'react-mdl/src/List/ListItem'>;
}
declare module 'react-mdl/src/List/ListItemAction.js' {
  declare module.exports: $Exports<'react-mdl/src/List/ListItemAction'>;
}
declare module 'react-mdl/src/List/ListItemContent.js' {
  declare module.exports: $Exports<'react-mdl/src/List/ListItemContent'>;
}
declare module 'react-mdl/src/Menu.js' {
  declare module.exports: $Exports<'react-mdl/src/Menu'>;
}
declare module 'react-mdl/src/ProgressBar.js' {
  declare module.exports: $Exports<'react-mdl/src/ProgressBar'>;
}
declare module 'react-mdl/src/Radio.js' {
  declare module.exports: $Exports<'react-mdl/src/Radio'>;
}
declare module 'react-mdl/src/RadioGroup.js' {
  declare module.exports: $Exports<'react-mdl/src/RadioGroup'>;
}
declare module 'react-mdl/src/Slider.js' {
  declare module.exports: $Exports<'react-mdl/src/Slider'>;
}
declare module 'react-mdl/src/Snackbar/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Snackbar/index'>;
}
declare module 'react-mdl/src/Spinner.js' {
  declare module.exports: $Exports<'react-mdl/src/Spinner'>;
}
declare module 'react-mdl/src/Switch.js' {
  declare module.exports: $Exports<'react-mdl/src/Switch'>;
}
declare module 'react-mdl/src/Tabs/index.js' {
  declare module.exports: $Exports<'react-mdl/src/Tabs/index'>;
}
declare module 'react-mdl/src/Tabs/Tab.js' {
  declare module.exports: $Exports<'react-mdl/src/Tabs/Tab'>;
}
declare module 'react-mdl/src/Tabs/TabBar.js' {
  declare module.exports: $Exports<'react-mdl/src/Tabs/TabBar'>;
}
declare module 'react-mdl/src/Tabs/Tabs.js' {
  declare module.exports: $Exports<'react-mdl/src/Tabs/Tabs'>;
}
declare module 'react-mdl/src/Textfield.js' {
  declare module.exports: $Exports<'react-mdl/src/Textfield'>;
}
declare module 'react-mdl/src/Tooltip.js' {
  declare module.exports: $Exports<'react-mdl/src/Tooltip'>;
}
declare module 'react-mdl/src/utils/basicClassCreator.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/basicClassCreator'>;
}
declare module 'react-mdl/src/utils/cloneChildren.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/cloneChildren'>;
}
declare module 'react-mdl/src/utils/MDLComponent.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/MDLComponent'>;
}
declare module 'react-mdl/src/utils/mdlUpgrade.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/mdlUpgrade'>;
}
declare module 'react-mdl/src/utils/palette.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/palette'>;
}
declare module 'react-mdl/src/utils/shadows.js' {
  declare module.exports: $Exports<'react-mdl/src/utils/shadows'>;
}
declare module 'react-mdl/tests.webpack.js' {
  declare module.exports: $Exports<'react-mdl/tests.webpack'>;
}
