// flow-typed signature: 6c60e39b1198ea4c4c455fefbbce08cb
// flow-typed version: <<STUB>>/stylelint-webpack-plugin_v^0.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-webpack-plugin/lib/linter' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/lib/run-compilation' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test1/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test2/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test3/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test4/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test5/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test6/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test7/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test8/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/fixtures/test9/index' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/helpers/pack' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/helpers/setup' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-webpack-plugin/index' {
  declare module.exports: $Exports<'stylelint-webpack-plugin'>;
}
declare module 'stylelint-webpack-plugin/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin'>;
}
declare module 'stylelint-webpack-plugin/lib/linter.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/linter'>;
}
declare module 'stylelint-webpack-plugin/lib/run-compilation.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/run-compilation'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test1/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test1/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test2/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test2/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test3/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test3/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test4/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test4/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test5/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test5/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test6/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test6/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test7/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test7/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test8/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test8/index'>;
}
declare module 'stylelint-webpack-plugin/test/fixtures/test9/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/fixtures/test9/index'>;
}
declare module 'stylelint-webpack-plugin/test/helpers/pack.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/helpers/pack'>;
}
declare module 'stylelint-webpack-plugin/test/helpers/setup.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/helpers/setup'>;
}
declare module 'stylelint-webpack-plugin/test/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/test/index'>;
}
