// flow-typed signature: 92b979ade1254d9446157e99a12eb68c
// flow-typed version: <<STUB>>/stylefmt-loader_v^1.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylefmt-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylefmt-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylefmt-loader/stylefmt-loader' {
  declare module.exports: any;
}

declare module 'stylefmt-loader/tests/example/test' {
  declare module.exports: any;
}

declare module 'stylefmt-loader/tests/example/webpack.config' {
  declare module.exports: any;
}

declare module 'stylefmt-loader/tests/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylefmt-loader/stylefmt-loader.js' {
  declare module.exports: $Exports<'stylefmt-loader/stylefmt-loader'>;
}
declare module 'stylefmt-loader/tests/example/test.js' {
  declare module.exports: $Exports<'stylefmt-loader/tests/example/test'>;
}
declare module 'stylefmt-loader/tests/example/webpack.config.js' {
  declare module.exports: $Exports<'stylefmt-loader/tests/example/webpack.config'>;
}
declare module 'stylefmt-loader/tests/loader.js' {
  declare module.exports: $Exports<'stylefmt-loader/tests/loader'>;
}
