// flow-typed signature: 09a40df2e7d07cc24dcfdb980d300da6
// flow-typed version: <<STUB>>/webpack-notifier_v^1.4.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-notifier/index' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
declare module 'webpack-notifier/index.js' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
